### ISSUE TITLE
Feature to bookmark articles

### ISSUE THREAD

**Issue by ShaishavGandhi** [ZacSweers/CatchUp#102]
The app could add the ability to bookmark articles. This could be useful in multiple ways. You could use it as a "read-later" of sorts or you could use it to save really good articles. 

There could be an additional tab which has all bookmarked articles.

**Comment by hzsweers** [comment]
What would clearing these look like? Just un-bookmarking them?

**Comment by shaishavgandhi05** [comment]
Yup. Could just un-bookmark by using same action as you did for bookmarking. I.e long press to reveal menu etc.

**Comment by shaishavgandhi05** [comment]
Hey @hzsweers any thoughts on this? Would love to take a stab at this and see how it turns out.

**Comment by hzsweers** [comment]
Sorry I've been traveling and haven't had time to think more on this. Open to proposals, but I think it's hard to see where it nicely fits in at the moment. One thought is maybe items should be expandable on longpress to expose more options, similar to Flamingo.
