### ISSUE TITLE
Weird pull-to-collapse behavior in smmry screen

### ISSUE THREAD

**Issue by saket** [ZacSweers/CatchUp#134]
I can't tell why, but pull gestures that start on empty areas seem to pull the `AppBarLayout`. Here's a video:

https://streamable.com/t8hw6

**Comment by hzsweers** [comment]
Yeah this is an issue with appbarlayout I think :/. Not sure what to do about it, happened when I was doing something else here before as well

**Comment by ZacSweers** [comment]
Closing for now as this feature is being changed to a fragment that sits atop the main view hierarchy
