### ISSUE TITLE
Use gradient for ic_launcher_background instead of a PNG

### ISSUE THREAD

**Issue by Piyush7890** [ZacSweers/CatchUp#140]

**Comment by hzsweers** [comment]
Could you add a bit more detail?

**Comment by Piyush7890** [comment]
<img width="425" alt="ic_launcher_background" src="https://user-images.githubusercontent.com/25117135/48690528-f2a13980-ebf4-11e8-98af-fd344dae53ae.PNG">

This will be  ic_launcher_background.xml


<img width="408" alt="icon_gradient" src="https://user-images.githubusercontent.com/25117135/48690553-14022580-ebf5-11e8-9079-97aa6cbf30ad.PNG">
 
this will be the icon_gradient.xml



<img width="725" alt="finally" src="https://user-images.githubusercontent.com/25117135/48690568-22e8d800-ebf5-11e8-8ade-9a64d591a4b1.PNG">

and u get the same effect.

this will reduce the apk size.
Just one ic_launcher_background.xml file for all resolutions

**Comment by hzsweers** [comment]
Want to send a PR?

**Comment by gpunto** [comment]
This looks like a simple fix! If you want I can send a PR

**Comment by ZacSweers** [comment]
Sure!
