### ISSUE TITLE
The Web Version

### ISSUE THREAD

**Issue by Omkaragrawal** [ZacSweers/CatchUp#145]
Hey developers of CatchUp,
Recently I was trying to build the web version of this app. I have tried building a basic webpage which currently supports just HACKERNEWS. I was wondering if we could combine both of the projects into one. 
We would have a web version(trying to shift to PWA since we can convert them to most platform supporting app) of this awesomely great android app.

I have hosted the app [HERE](https://catchupweb.herokuapp.com/)

**Comment by ZacSweers** [comment]
Thanks but not looking to merge this project with any others

**Comment by ZacSweers** [comment]
Also - would prefer you not use this app's icon for your website, as it's not affiliated with this app nor does it even offer any appropriate attribution to this project

**Comment by Omkaragrawal** [comment]
OK I will surely remove the icon if you say so but is there anyway that we can negotiate on having a web version (even if in another repo).

Currently I am just working on back-end and I will make it feel like the android app so don't assume the current UI as final.

Plus I will be mentioning & linking this repo+playstore of this app in the navbar (since currently I am just focused at back-end. I will be doing UI afterwards).

**Comment by ZacSweers** [comment]
Sorry but I'm not interested.
