### ISSUE TITLE
[Feature request] Support Lobsters

### ISSUE THREAD

**Issue by KevCui** [ZacSweers/CatchUp#153]
Is it possible to add Lobsters as a service in CatchUp?
URL: https://lobste.rs
Code: https://github.com/lobsters/lobsters

**Comment by ZacSweers** [comment]
Sure! Want to send a PR? The structure of the other services should be easy to follow

**Comment by KevCui** [comment]
I want but not sure if I can. I will start to read code and try out someting. btw, testing part is amazing :smile:
