### ISSUE TITLE
Support for economic sources

### ISSUE THREAD

**Issue by Bram1337** [ZacSweers/CatchUp#167]
Pity this app is quatched atm as we all know it converges best.
I had an idea which is to add a few prestigious economical sources.

I felt I had consumed plethora of tech that I desired divergent schemata.
What about adding "Economist's View" and "Vox EU" for macro reflecting(s)?

I believe with the offset of Artifrictional Intelligence this may be the missing linkage.

**Comment by ZacSweers** [comment]
Sorry not taking requests right now!
