### ISSUE TITLE
Publish on F-Droid (free/libre open source app store)

### ISSUE THREAD

**Issue by heyakyra** [ZacSweers/CatchUp#180]
Since there have been problems with Play Store policy, this would be a nice way to make it widely available still. 

https://f-droid.org/

**Comment by ZacSweers** [comment]
The play store problem was resolved, I just haven't circled back to releasing yet since it's a hobby project. I'll do it soon, in the meantime building from source should work fine :)

**Comment by heyakyra** [comment]
Couldn't you still publish on both? Some android users may not have the Play store

**Comment by ZacSweers** [comment]
Sorry I'm not interested in publishing to other app stores
