### ISSUE TITLE
WHy does the project not build out of the box?

### ISSUE THREAD

**Issue by dhaksddj** [ZacSweers/CatchUp#392]
```
The project is using an incompatible preview version (AGP 8.0.0-alpha08) of the Android Gradle plugin. Current compatible preview version is AGP 8.0.0-alpha10.
Upgrade to a supported version
See Android Studio & AGP compatibility options.
```

I am running Flamingo 2022.2.1 Canary 10 (latest).

The readme says look at `libs.versions.toml`, however I cannot find it in the project.

**Comment by ZacSweers** [comment]
It's at gradle/libs.versions.toml and the agp version (at the time of writing) is one line 3 and set to 8.0.0-alpha10. It builds just fine out of the box, closing this.
