### ISSUE TITLE
Improving perf in list load

### ISSUE THREAD

**Issue by ZacSweers** [ZacSweers/CatchUp#48]
Some prior art in #18 #39

Currently there are some jitters in lists. Ideas for improving this:
- Switch items to ConstraintLayout
  - I for the life of me can't get them to work every time I've tried. They look fine in the editor, then explode at runtime.
- Switch to Litho
  - Probably most performant, but also pretty different
- Arch components paging (#39)
  - Could be done in tandem with the rest here
- Use spannablestrings for attribution and header texts to reduce view count
  - This could possibly make ConstraintLayout easier

**Comment by hzsweers** [comment]
Another option https://facebookincubator.github.io/TextLayoutBuilder/
