### ISSUE TITLE
Reporting Vulnerability

### ISSUE THREAD

**Issue by igibek** [ZacSweers/CatchUp#633]
Hello! 

I hope you are doing well!

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it?

Thanks in advance!

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by ZacSweers** [comment]
Please stop spamming people

<img width="432" alt="image" src="https://user-images.githubusercontent.com/1361086/230909863-956d194e-2897-4aa2-bd69-3713919b23de.png">
